# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 08:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_auto_20160816_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='date_of_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 16, 8, 2, 51, 274725, tzinfo=utc), null=True, verbose_name='\u0414\u0430\u0442\u0430 \u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='note.Group', verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430'),
        ),
    ]
